- name: Debug Command
  run: |
    git --version
    echo "Before SHA: ${{ github.event.before }}"
    echo "Current SHA: ${{ github.sha }}"
    CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
    echo "Changed Files: $CHANGED_FILES"
    if [ -n "$CHANGED_FILES" ]; then
      CHANGED=true
    else
      CHANGED=false
    fi
    echo "Changed flag: $CHANGED"
