- name: Debug Command
  run: |
    git --version
    echo "Before SHA: ${{ github.event.before }}"
    echo "Current SHA: ${{ github.sha }}"
    CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
    echo "Changed Files: $CHANGED_FILES"
    echo "$CHANGED_FILES" | grep . && CHANGED=true || CHANGED=false
    echo "Changed flag: $CHANGED"
