name: Auto Comment on Repository Changes

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Repository Files Changed
        run: |
          git fetch --prune --unshallow
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$CHANGED_FILES" | grep . && CHANGED=true || CHANGED=false

      - name: Create Comment
        if: ${{ env.CHANGED == 'true' }}
        uses: actions/github-script@0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = "[Auto-Comment]: Changes detected in the repository. We will review the updates shortly.";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
