name: Auto Comment on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  auto-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR Paths Match
        run: |
          PR_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          echo "$PR_FILES" | grep -qE '^features/' || exit 1

      - name: Create Comment
        if: ${{ success() }}
        uses: actions/github-script@0.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = "[Auto-Comment]: Thank you for your pull request! 🙌 We will review it shortly.";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
